### ISSUE TITLE
CSS coding style doesn't talk about CSS values and Units Ex: px, rem, lh, vh etc

### ISSUE THREAD

**Issue by HimanshuAgrahari07** [OsmosysSoftware/dev-standards#21]

**Comment by osm-vishnukyatannawar** [comment]
@vikas-kyatannawar 

can you check and see what we have already?

@HimanshuAgrahari07  

can you let us know what standards you want us to include in CSS standards?

**Comment by vikas-kyatannawar** [comment]
I don't think we can keep a standard on those. Those values are something which we use based on our requirements.

**Comment by osm-vishnukyatannawar** [comment]
As of now we are good.

Closing this issue.

Please feel free to reopen if required.
